### ISSUE TITLE
getAppStatus() returns nil on recent watch software versions

### ISSUE THREAD

**Issue by sorinspd** [garmin/connectiq-companion-app-sdk-ios#1]
for example: epix2 software version 14.36
also reproduced with: tactix7, fenix7, instinct 2x, descent

older software versions work correctly, for example:
- venu 2 plus version 15.20
- fenix 6s pro version 24.00

there is also the following message while running the companion app in Xcode:
API MISUSE: <CBCentralManager: 0x283b66f80> has no restore identifier but the delegate implements the centralManager:willRestoreState: method. Restoring will not be supported

btw, this issue affects the example app as well

**Comment by dherschberger** [comment]
Hi @sorinspd, version 1.5.1 has been published here. The example app has been updated to use 1.5.1 as well. This should resolve the issue connecting with some products and should eliminate the warning about restoring Bluetooth peripheral state. Thanks!

**Comment by sorinspd** [comment]
can confirm it works fine now. thank you for taking action
